import React from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const PrivacyPolicy: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-4xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <Button 
            variant="ghost" 
            onClick={() => navigate(-1)} 
            className="mb-4"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back
          </Button>
          <h1 className="text-3xl font-bold text-foreground mb-2">RezLit Privacy Policy</h1>
          <p className="text-muted-foreground">Effective Date: 7 July 2025</p>
        </div>

        <Card>
          <CardContent className="p-8 prose prose-lg max-w-none">
            <div className="space-y-8">
              <section>
                <p className="text-muted-foreground leading-relaxed">
                  RezLit, Inc. ("RezLit," "we," "our," or "us") respects your privacy. This Policy explains how we collect, use, disclose, and safeguard your information when you visit RezLit.com or use our related services (collectively, the "Platform").
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-4">1. Scope</h2>
                <div className="text-muted-foreground leading-relaxed space-y-3">
                  <p>This Policy applies to information we process about:</p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>Job seekers who create an account or upload application materials.</li>
                    <li>Employers/recruiters who post roles.</li>
                    <li>Visitors who browse the Platform without logging in.</li>
                  </ul>
                  <p>It does not cover third-party sites or services that link to or from RezLit.</p>
                </div>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-4">2. Information We Collect</h2>
                <div className="text-muted-foreground leading-relaxed space-y-4">
                  <div className="overflow-x-auto">
                    <table className="w-full border-collapse border border-gray-300">
                      <thead>
                        <tr className="bg-gray-50">
                          <th className="border border-gray-300 px-4 py-2 text-left font-semibold">Category</th>
                          <th className="border border-gray-300 px-4 py-2 text-left font-semibold">Examples</th>
                          <th className="border border-gray-300 px-4 py-2 text-left font-semibold">Source</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">Account Data</td>
                          <td className="border border-gray-300 px-4 py-2">Name, email, password hash, phone, location, marketing-opt-in flag</td>
                          <td className="border border-gray-300 px-4 py-2">You</td>
                        </tr>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">Profile & Application Data</td>
                          <td className="border border-gray-300 px-4 py-2">Resume/CV, cover letters, work eligibility, salary expectations, questionnaire answers, interview recordings/transcripts</td>
                          <td className="border border-gray-300 px-4 py-2">You</td>
                        </tr>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">Job-Match Signals</td>
                          <td className="border border-gray-300 px-4 py-2">Skills parsed from your résumé, ATS scores, AI interview feedback</td>
                          <td className="border border-gray-300 px-4 py-2">Generated by our AI tools</td>
                        </tr>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">Usage & Device Data</td>
                          <td className="border border-gray-300 px-4 py-2">IP address, browser type, referral URL, clicks, pages viewed, session timestamps, cookies</td>
                          <td className="border border-gray-300 px-4 py-2">Automatic</td>
                        </tr>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">Communications</td>
                          <td className="border border-gray-300 px-4 py-2">Support tickets, chat messages, email content</td>
                          <td className="border border-gray-300 px-4 py-2">You</td>
                        </tr>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">Marketing Preferences</td>
                          <td className="border border-gray-300 px-4 py-2">Role-alert topics, unsubscribe status</td>
                          <td className="border border-gray-300 px-4 py-2">You</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <p><strong>Sensitive data:</strong> We do not request SSNs, credit-card numbers, or government IDs. Voluntary demographic/EEO forms are stored separately and used only in aggregate.</p>
                </div>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-4">3. How & Why We Use Your Information</h2>
                <div className="text-muted-foreground leading-relaxed space-y-4">
                  <div className="overflow-x-auto">
                    <table className="w-full border-collapse border border-gray-300">
                      <thead>
                        <tr className="bg-gray-50">
                          <th className="border border-gray-300 px-4 py-2 text-left font-semibold">Purpose</th>
                          <th className="border border-gray-300 px-4 py-2 text-left font-semibold">Legal Basis¹</th>
                          <th className="border border-gray-300 px-4 py-2 text-left font-semibold">Details</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">Provide core services (resume parsing, job matching, interview simulations)</td>
                          <td className="border border-gray-300 px-4 py-2">Contract</td>
                          <td className="border border-gray-300 px-4 py-2">Operate user accounts, display job listings, generate AI insights</td>
                        </tr>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">Email alerts for relevant roles</td>
                          <td className="border border-gray-300 px-4 py-2">Consent</td>
                          <td className="border border-gray-300 px-4 py-2">Opt-in at sign-up; unsubscribe anytime</td>
                        </tr>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">Improve & secure the Platform</td>
                          <td className="border border-gray-300 px-4 py-2">Legitimate Interest</td>
                          <td className="border border-gray-300 px-4 py-2">Debug, prevent fraud, analyze usage, train internal ML models</td>
                        </tr>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">Compliance & legal obligations</td>
                          <td className="border border-gray-300 px-4 py-2">Legal Obligation</td>
                          <td className="border border-gray-300 px-4 py-2">Tax, accounting, court orders</td>
                        </tr>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">Marketing, surveys, and product updates</td>
                          <td className="border border-gray-300 px-4 py-2">Consent / Legitimate Interest</td>
                          <td className="border border-gray-300 px-4 py-2">We keep it minimal and relevant</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <p className="text-sm italic">¹For EU/UK users under GDPR; U.S. users rely mainly on contract & consent.</p>
                </div>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-4">4. Cookies & Tracking</h2>
                <p className="text-muted-foreground leading-relaxed">
                  We use first-party cookies for login sessions and preference storage, plus limited third-party analytics (e.g., Hotjar, Plausible). We do not serve behavior-based advertising. You can control cookies via browser settings; however, essential cookies are required for core functionality.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-4">5. Disclosure of Information</h2>
                <div className="text-muted-foreground leading-relaxed space-y-3">
                  <p>We share data only as needed to run the Platform:</p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li><strong>Service Providers</strong> – Supabase (database & auth), Resend (transactional email), n8n (workflow automation), Apify/SerpAPI (job-data ingestion), OpenAI LLC (AI processing).</li>
                    <li><strong>Recruiters/Employers</strong> – When you actively apply or make your profile searchable.</li>
                    <li><strong>Analytics & Security Partners</strong> – Error tracking, load balancing, DDoS protection.</li>
                    <li><strong>Legal</strong> – To comply with law or protect rights, property, or safety.</li>
                  </ul>
                  <p>We never sell or rent your personal information.</p>
                </div>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-4">6. International Transfers</h2>
                <p className="text-muted-foreground leading-relaxed">
                  We host data in the United States. If you access RezLit from outside the U.S., you consent to transferring your data to, and processing in, the U.S. where privacy laws may differ.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-4">7. Data Retention</h2>
                <div className="text-muted-foreground leading-relaxed space-y-3">
                  <p><strong>Active accounts:</strong> we retain data while your account exists.</p>
                  <p><strong>Closed accounts:</strong> we delete or anonymize data within 90 days, unless retention is required by law or to resolve disputes.</p>
                  <p><strong>Log files & backups:</strong> typically stored for 30–180 days.</p>
                </div>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-4">8. Security</h2>
                <p className="text-muted-foreground leading-relaxed">
                  We use industry-standard measures: encryption in transit (TLS 1.3), hashed passwords (argon2id), scoped API keys, and role-based access. No system is 100% secure, so please keep credentials confidential and notify us of any suspected breach.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-4">9. Your Choices & Rights</h2>
                <div className="text-muted-foreground leading-relaxed space-y-4">
                  <div className="overflow-x-auto">
                    <table className="w-full border-collapse border border-gray-300">
                      <thead>
                        <tr className="bg-gray-50">
                          <th className="border border-gray-300 px-4 py-2 text-left font-semibold">If you are...</th>
                          <th className="border border-gray-300 px-4 py-2 text-left font-semibold">You may...</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">All users</td>
                          <td className="border border-gray-300 px-4 py-2">Access, correct, or delete profile data via account settings • Opt out of marketing emails</td>
                        </tr>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">EU/UK</td>
                          <td className="border border-gray-300 px-4 py-2">Request data portability • Object to processing • Restrict processing • Lodge a complaint with your local DPA</td>
                        </tr>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2">California resident</td>
                          <td className="border border-gray-300 px-4 py-2">Request to know, delete, or correct personal info • Opt out of any future "selling" or "sharing" (we do not sell)</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <p>Submit rights requests to privacy@rezlit.com. We will verify your identity before fulfilling.</p>
                </div>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-4">10. Children</h2>
                <p className="text-muted-foreground leading-relaxed">
                  RezLit is not directed to anyone under 16. We do not knowingly collect data from children. If you believe a minor has provided data, contact us for deletion.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-4">11. Changes to This Policy</h2>
                <p className="text-muted-foreground leading-relaxed">
                  We may update this Policy periodically. Material changes will be announced via email or in-app notice. Continued use after the effective date means you accept the revised Policy.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-4">12. Contact Us</h2>
                <div className="text-muted-foreground leading-relaxed space-y-2">
                  <p><strong>RezLit, Inc.</strong></p>
                  <p>Attn: Privacy Team</p>
                  <p>Email: privacy@rezlit.com</p>
                </div>
              </section>
            </div>
          </CardContent>
        </Card>

        {/* Footer */}
        <div className="mt-8 text-center">
          <Button 
            variant="outline"
            onClick={() => navigate('/')}
          >
            Return to Home
          </Button>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;