// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuthirgvlzyzgmyxyzpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1dGhpcmd2bHp5emdteXh5enByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Njg2OTEsImV4cCI6MjA2NjA0NDY5MX0.Wedl58iRdtSBEyj9S4AoPv6H0HgFUSx8ixBtZfnOcRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);